# Generated by Django 5.1.3 on 2024-12-21 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_sys', '0001_initial'),
        ('forum_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryview',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_system.category'),
        ),
        migrations.AddField(
            model_name='categoryview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topicview',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_system.topic'),
        ),
        migrations.AddField(
            model_name='topicview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='categoryview',
            unique_together={('user', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='topicview',
            unique_together={('user', 'topic')},
        ),
    ]
