# Generated by Django 5.1.3 on 2024-12-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media/images/portfolio/'),
        ),
    ]
