# Generated by Django 5.1.3 on 2024-12-21 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('quick_access_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_accessed_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'quick_access_to')},
            },
        ),
    ]
