# Generated by Django 5.1.3 on 2024-12-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0004_savedaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='link_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
