# Generated by Django 5.1.3 on 2024-12-20 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0005_categoryview'),
        ('forum_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryview',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum_system.category'),
        ),
    ]
