# Generated by Django 5.1.3 on 2024-12-19 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id']},
        ),
    ]
