# Generated by Django 5.1.1 on 2024-12-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/gallery/'),
        ),
    ]
