# Generated by Django 5.1.3 on 2024-12-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='topic',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
