# Generated by Django 5.1.3 on 2024-12-08 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_system', '0002_poll_polloption_vote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polloption',
            name='option_text',
        ),
        migrations.AddField(
            model_name='polloption',
            name='votes',
            field=models.ManyToManyField(related_name='poll_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vote',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to='forum_system.polloption'),
        ),
    ]
