# Generated by Django 5.1.3 on 2024-12-08 16:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_system', '0003_remove_polloption_option_text_polloption_votes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='polloption',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='poll_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
