<<<<<<< HEAD
# Generated by Django 5.1.1 on 2024-12-16 17:16

=======
# Generated by Django 5.1.1 on 2024-12-14 19:27

from django.conf import settings
>>>>>>> 301c715cf2637abb8031b0c35d9cbceaf68cceae
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 301c715cf2637abb8031b0c35d9cbceaf68cceae
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('theme', models.CharField(max_length=80)),
                ('presence', models.CharField(choices=[('missing', 'Missing'), ('present', 'Present')], default='missing', max_length=27)),
                ('grade', models.IntegerField()),
                ('homework', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('done', 'Done'), ('in_progress', 'In progress'), ('to_do', 'To do')], default='to_do', max_length=27)),
                ('file', models.FileField(blank=True, null=True, upload_to='comments_media/')),
=======
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('lesson_date', models.DateTimeField()),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('user', models.ManyToManyField(related_name='Grade', to=settings.AUTH_USER_MODEL)),
>>>>>>> 301c715cf2637abb8031b0c35d9cbceaf68cceae
            ],
        ),
    ]
