# Generated by Django 5.1.1 on 2024-12-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('theme', models.CharField(max_length=80)),
                ('presence', models.CharField(choices=[('missing', 'Відсутній'), ('present', 'Присутній')], default='missing', max_length=27)),
                ('grade', models.IntegerField()),
                ('homework', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('done', 'Зроблено'), ('in_progress', 'Робиться'), ('to_do', 'Треба зробити')], default='to_do', max_length=27)),
                ('file', models.FileField(blank=True, null=True, upload_to='comments_media/')),
            ],
        ),
    ]
