# Generated by Django 5.1.3 on 2024-12-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='status',
            field=models.CharField(choices=[('done', 'Зроблено'), ('in_progress', 'Робиться'), ('to_do', 'Треба зробити')], default='to_do', max_length=27),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='presence',
            field=models.CharField(choices=[('missing', 'Відсутній'), ('present', 'Присутній')], default='missing', max_length=27),
        ),
    ]
