# Generated by Django 5.1.3 on 2024-12-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('homework', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('done', 'Done'), ('in_progress', 'In progress'), ('to_do', 'To do')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='comments_media/')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('theme', models.CharField(max_length=80)),
                ('presence', models.CharField(choices=[('present', 'Present'), ('missing', 'Missing')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
