# Generated by Django 5.1.3 on 2024-12-08 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_system', '0002_homework_lesson_delete_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='daily_system.lesson'),
        ),
    ]
