# Generated by Django 5.1.3 on 2024-12-17 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_system', '0003_userannouncement_delete_userannouncementstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAnnouncement',
        ),
    ]
