# Generated by Django 5.1.3 on 2024-12-18 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['-id']},
        ),
    ]
